# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  # Event for the workflow to run on
  push:
    branches:
      - 'main' 

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
      with:
        path: build # change to your build folder
        install_command: yarn install # default: npm ci
        build_command: yarn build-storybook # default: npm run build-storybook
        path: storybook-static # default: dist/storybook