name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint && yarn build
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}